### PR TITLE
resolve bug: change from lead to contact when adding remark

### LINKED ISSUE #59: Adding a remark converts a lead into a contact

### PR DESCRIPTION
**Pull request by zhuleyan**
resolve #59

### CODE REVIEW

**Comment by davidten** [comment]
Can @WoodyLau review this

File: src/test/java/seedu/address/logic/commands/RemarkCommandTest.java [hunk 1]
```diff
@@ -36,7 +36,7 @@
     @Test
     public void execute_addRemarkUnfilteredList_success() throws Exception {
         Person firstPerson = model.getFilteredPersonList().get(INDEX_FIRST_PERSON.getZeroBased());
-        Person editedPerson = new PersonBuilder(firstPerson).withRemark(REMARK_EXAMPLE).buildRegardlessOfType();
+        Person editedPerson = new PersonBuilder(firstPerson).withRemark(REMARK_EXAMPLE).build();
```
Comment (WoodyLau) [inline src/test/java/seedu/address/logic/commands/RemarkCommandTest.java]: In these test cases, we should test for a similar situation as we just encountered; as in, remarking on a Lead or Contact won't change it to the other type.

Right now, you've only tested on FIRST_PERSON, who I think is a Lead. Please check a Contact too.
